--- 
title: "Practical 4 - Transforming variables and further examining model assumptions"
author: "Megan Ruffle"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---

# Introduction

```{r eval=FALSE, echo=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

```{r setup, include=FALSE, eval=TRUE}
library(webexercises)
library(tinytex)
library(ggplot2)
library(dplyr)
library(knitr)
library(PASWR2)
life <- read.csv("LifeExp.csv")
stopping <- read.csv("stopping.csv")
mammals <- read.csv("MammalWeight.csv")
library(MASS)
```

## Intended Learning Outcomes
- fit linear models with transformed variables;
- produce residual plots and assess the assumptions of a linear model.
